import { TrainingGoal, HabitLevel, WeekDay, WorkoutExercise, FitnessPillar, SportChoice } from '@/types/training';

export const FITNESS_PILLARS: FitnessPillar[] = [
  {
    id: 'cardio',
    name: 'Cardio',
    description: 'Improve cardiovascular health and endurance',
    icon: 'heart',
    selected: false,
  },
  {
    id: 'strength',
    name: 'Strength',
    description: 'Build muscle mass and raw power',
    icon: 'dumbbell',
    selected: false,
  },
  {
    id: 'mobility',
    name: 'Mobility',
    description: 'Enhance flexibility and range of motion',
    icon: 'flower',
    selected: false,
  },
  {
    id: 'muscular-endurance',
    name: 'Muscular Endurance',
    description: 'Build stamina and resistance to fatigue',
    icon: 'zap',
    selected: false,
  },
  {
    id: 'balance-stability',
    name: 'Balance & Stability',
    description: 'Improve coordination and core stability',
    icon: 'target',
    selected: false,
  },
  {
    id: 'speed',
    name: 'Speed',
    description: 'Develop quickness and explosive power',
    icon: 'zap-off',
    selected: false,
  },
];

export const SPORT_CHOICES: SportChoice[] = [
  {
    id: 'soccer',
    name: 'Soccer',
    description: 'Team sport requiring endurance and agility',
    icon: '⚽',
    recommendedPillars: [
      { pillarId: 'cardio', importance: 5 },
      { pillarId: 'speed', importance: 4 },
      { pillarId: 'muscular-endurance', importance: 4 },
      { pillarId: 'balance-stability', importance: 4 },
      { pillarId: 'mobility', importance: 3 },
      { pillarId: 'strength', importance: 3 },
    ],
  },
  {
    id: 'basketball',
    name: 'Basketball',
    description: 'Fast-paced sport requiring jumping and agility',
    icon: '🏀',
    recommendedPillars: [
      { pillarId: 'speed', importance: 5 },
      { pillarId: 'strength', importance: 4 },
      { pillarId: 'cardio', importance: 4 },
      { pillarId: 'balance-stability', importance: 4 },
      { pillarId: 'muscular-endurance', importance: 3 },
      { pillarId: 'mobility', importance: 3 },
    ],
  },
  {
    id: 'tennis',
    name: 'Tennis',
    description: 'Racquet sport requiring agility and endurance',
    icon: '🎾',
    recommendedPillars: [
      { pillarId: 'speed', importance: 5 },
      { pillarId: 'cardio', importance: 4 },
      { pillarId: 'balance-stability', importance: 4 },
      { pillarId: 'muscular-endurance', importance: 4 },
      { pillarId: 'mobility', importance: 3 },
      { pillarId: 'strength', importance: 3 },
    ],
  },
  {
    id: 'american-football',
    name: 'American Football',
    description: 'High-intensity contact sport requiring power',
    icon: '🏈',
    recommendedPillars: [
      { pillarId: 'strength', importance: 5 },
      { pillarId: 'speed', importance: 5 },
      { pillarId: 'balance-stability', importance: 4 },
      { pillarId: 'muscular-endurance', importance: 4 },
      { pillarId: 'cardio', importance: 3 },
      { pillarId: 'mobility', importance: 3 },
    ],
  },
  {
    id: 'rugby',
    name: 'Rugby',
    description: 'Physical team sport requiring strength and endurance',
    icon: '🏉',
    recommendedPillars: [
      { pillarId: 'strength', importance: 5 },
      { pillarId: 'cardio', importance: 4 },
      { pillarId: 'muscular-endurance', importance: 4 },
      { pillarId: 'balance-stability', importance: 4 },
      { pillarId: 'speed', importance: 3 },
      { pillarId: 'mobility', importance: 3 },
    ],
  },
  {
    id: 'swimming',
    name: 'Swimming',
    description: 'Full-body low-impact endurance sport',
    icon: '🏊',
    recommendedPillars: [
      { pillarId: 'cardio', importance: 5 },
      { pillarId: 'muscular-endurance', importance: 5 },
      { pillarId: 'mobility', importance: 4 },
      { pillarId: 'strength', importance: 3 },
      { pillarId: 'balance-stability', importance: 2 },
      { pillarId: 'speed', importance: 2 },
    ],
  },
  {
    id: 'running',
    name: 'Running',
    description: 'Endurance sport for cardiovascular fitness',
    icon: '🏃',
    recommendedPillars: [
      { pillarId: 'cardio', importance: 5 },
      { pillarId: 'muscular-endurance', importance: 4 },
      { pillarId: 'mobility', importance: 3 },
      { pillarId: 'strength', importance: 3 },
      { pillarId: 'balance-stability', importance: 2 },
      { pillarId: 'speed', importance: 2 },
    ],
  },
  {
    id: 'cycling',
    name: 'Cycling',
    description: 'Endurance sport on two wheels',
    icon: '🚴',
    recommendedPillars: [
      { pillarId: 'cardio', importance: 5 },
      { pillarId: 'muscular-endurance', importance: 4 },
      { pillarId: 'strength', importance: 3 },
      { pillarId: 'mobility', importance: 3 },
      { pillarId: 'balance-stability', importance: 2 },
      { pillarId: 'speed', importance: 2 },
    ],
  },
  {
    id: 'triathlon',
    name: 'Triathlon',
    description: 'Multi-discipline endurance sport',
    icon: '🏊‍♂️',
    recommendedPillars: [
      { pillarId: 'cardio', importance: 5 },
      { pillarId: 'muscular-endurance', importance: 5 },
      { pillarId: 'mobility', importance: 4 },
      { pillarId: 'strength', importance: 3 },
      { pillarId: 'balance-stability', importance: 3 },
      { pillarId: 'speed', importance: 2 },
    ],
  },
  {
    id: 'boxing',
    name: 'Boxing',
    description: 'Combat sport requiring power and agility',
    icon: '🥊',
    recommendedPillars: [
      { pillarId: 'speed', importance: 5 },
      { pillarId: 'cardio', importance: 5 },
      { pillarId: 'strength', importance: 4 },
      { pillarId: 'balance-stability', importance: 4 },
      { pillarId: 'muscular-endurance', importance: 4 },
      { pillarId: 'mobility', importance: 3 },
    ],
  },
  {
    id: 'mma',
    name: 'MMA',
    description: 'Mixed martial arts requiring all-around fitness',
    icon: '🥋',
    recommendedPillars: [
      { pillarId: 'strength', importance: 5 },
      { pillarId: 'cardio', importance: 5 },
      { pillarId: 'mobility', importance: 5 },
      { pillarId: 'muscular-endurance', importance: 5 },
      { pillarId: 'speed', importance: 4 },
      { pillarId: 'balance-stability', importance: 4 },
    ],
  },
];

export const TRAINING_GOALS: TrainingGoal[] = [
  {
    id: 'cardio',
    name: 'Cardio',
    description: 'Improve cardiovascular health and endurance',
    icon: 'heart',
    selected: false,
  },
  {
    id: 'functional',
    name: 'Functional Training',
    description: 'Build practical strength for daily activities',
    icon: 'zap',
    selected: false,
  },
  {
    id: 'yoga',
    name: 'Yoga & Flexibility',
    description: 'Enhance flexibility, balance, and mindfulness',
    icon: 'flower',
    selected: false,
  },
  {
    id: 'strength',
    name: 'Strength Training',
    description: 'Build muscle mass and raw power',
    icon: 'dumbbell',
    selected: false,
  },
  {
    id: 'sports',
    name: 'Sports Performance',
    description: 'Improve athletic performance and agility',
    icon: 'trophy',
    selected: false,
  },
];

export const HABIT_LEVELS: HabitLevel[] = [
  {
    id: 'beginner',
    name: 'Just Starting',
    description: 'New to regular exercise, ready to build habits',
    changeReadiness: 5,
  },
  {
    id: 'inconsistent',
    name: 'Inconsistent',
    description: 'Exercise occasionally, want more structure',
    changeReadiness: 4,
  },
  {
    id: 'moderate',
    name: 'Moderately Active',
    description: 'Exercise 2-3 times per week regularly',
    changeReadiness: 3,
  },
  {
    id: 'consistent',
    name: 'Very Consistent',
    description: 'Exercise 4+ times per week, looking to optimize',
    changeReadiness: 2,
  },
  {
    id: 'athlete',
    name: 'Athlete Level',
    description: 'Train daily, seeking performance gains',
    changeReadiness: 1,
  },
];

export const WEEK_DAYS: WeekDay[] = [
  { id: 1, name: 'Monday', short: 'Mon', available: true },
  { id: 2, name: 'Tuesday', short: 'Tue', available: true },
  { id: 3, name: 'Wednesday', short: 'Wed', available: true },
  { id: 4, name: 'Thursday', short: 'Thu', available: true },
  { id: 5, name: 'Friday', short: 'Fri', available: true },
  { id: 6, name: 'Saturday', short: 'Sat', available: true },
  { id: 0, name: 'Sunday', short: 'Sun', available: true },
];

export const EXERCISE_DATABASE: { [key: string]: WorkoutExercise[] } = {
  // PURE CARDIO - Heart rate focused exercises only
  cardio: [
    {
      id: 'jumpingjacks',
      name: 'Jumping Jacks',
      reps: 30,
      sets: 3,
      restTime: 30,
      instructions: 'Jump while spreading your legs and raising your arms overhead. Return to starting position.',
      difficulty: 'beginner',
      targetMuscles: ['cardiovascular system'],
    },
    {
      id: 'highknees',
      name: 'High Knees',
      duration: 30,
      sets: 3,
      restTime: 30,
      instructions: 'Run in place, bringing your knees up to hip level with each step.',
      difficulty: 'beginner',
      targetMuscles: ['cardiovascular system'],
    },
    {
      id: 'butt-kicks',
      name: 'Butt Kicks',
      duration: 30,
      sets: 3,
      restTime: 30,
      instructions: 'Run in place, kicking your heels up to touch your glutes.',
      difficulty: 'beginner',
      targetMuscles: ['cardiovascular system'],
    },
    {
      id: 'step-ups',
      name: 'Step-ups',
      reps: 20,
      sets: 3,
      restTime: 45,
      instructions: 'Step up onto a platform or chair, then step back down. Alternate legs.',
      difficulty: 'beginner',
      targetMuscles: ['cardiovascular system'],
    },
    {
      id: 'cardio-dance',
      name: 'Cardio Dance',
      duration: 60,
      sets: 3,
      restTime: 60,
      instructions: 'Dance continuously with high-energy movements to keep heart rate elevated.',
      difficulty: 'intermediate',
      targetMuscles: ['cardiovascular system'],
    },
    {
      id: 'shadow-boxing',
      name: 'Shadow Boxing',
      duration: 45,
      sets: 3,
      restTime: 45,
      instructions: 'Throw punches in the air with continuous movement, keep feet moving.',
      difficulty: 'intermediate',
      targetMuscles: ['cardiovascular system'],
    },
    {
      id: 'running-in-place',
      name: 'Running in Place',
      duration: 45,
      sets: 4,
      restTime: 30,
      instructions: 'Run in place at a steady pace, pumping your arms naturally.',
      difficulty: 'beginner',
      targetMuscles: ['cardiovascular system'],
    },
    {
      id: 'star-jumps',
      name: 'Star Jumps',
      reps: 25,
      sets: 3,
      restTime: 45,
      instructions: 'Jump up spreading arms and legs wide like a star, then return to starting position.',
      difficulty: 'intermediate',
      targetMuscles: ['cardiovascular system'],
    },
    {
      id: 'cardio-kickboxing',
      name: 'Cardio Kickboxing',
      duration: 60,
      sets: 3,
      restTime: 60,
      instructions: 'Combine punches and kicks in a continuous flow, keeping heart rate elevated.',
      difficulty: 'intermediate',
      targetMuscles: ['cardiovascular system'],
    },
    {
      id: 'interval-sprints',
      name: 'Interval Sprints',
      duration: 20,
      sets: 6,
      restTime: 40,
      instructions: 'Sprint in place at maximum effort for 20 seconds, then rest.',
      difficulty: 'advanced',
      targetMuscles: ['cardiovascular system'],
    },
  ],
  
  // PURE STRENGTH - Muscle building focused exercises only
  strength: [
    {
      id: 'pushups',
      name: 'Push-ups',
      reps: 15,
      sets: 3,
      restTime: 60,
      instructions: 'Start in plank position. Lower your chest to the ground, keeping your body straight. Push back up to starting position.',
      difficulty: 'beginner',
      targetMuscles: ['chest', 'shoulders', 'triceps'],
    },
    {
      id: 'squats',
      name: 'Bodyweight Squats',
      reps: 20,
      sets: 3,
      restTime: 45,
      instructions: 'Stand with feet shoulder-width apart. Lower your hips back and down as if sitting in a chair. Return to standing.',
      difficulty: 'beginner',
      targetMuscles: ['quadriceps', 'glutes', 'hamstrings'],
    },
    {
      id: 'lunges',
      name: 'Forward Lunges',
      reps: 12,
      sets: 3,
      restTime: 45,
      instructions: 'Step forward with one leg, lowering your hips until both knees are bent at 90 degrees. Return to start and repeat.',
      difficulty: 'beginner',
      targetMuscles: ['quadriceps', 'glutes', 'hamstrings'],
    },
    {
      id: 'pullups',
      name: 'Pull-ups',
      reps: 8,
      sets: 3,
      restTime: 90,
      instructions: 'Hang from a bar with palms facing away. Pull your body up until your chin clears the bar. Lower with control.',
      difficulty: 'intermediate',
      targetMuscles: ['back', 'biceps'],
    },
    {
      id: 'dips',
      name: 'Tricep Dips',
      reps: 12,
      sets: 3,
      restTime: 60,
      instructions: 'Using parallel bars or a chair, lower your body by bending your arms. Push back up to starting position.',
      difficulty: 'intermediate',
      targetMuscles: ['triceps', 'shoulders', 'chest'],
    },
    {
      id: 'pike-pushups',
      name: 'Pike Push-ups',
      reps: 10,
      sets: 3,
      restTime: 60,
      instructions: 'Start in downward dog position. Lower your head toward the ground, then push back up.',
      difficulty: 'intermediate',
      targetMuscles: ['shoulders', 'triceps'],
    },
    {
      id: 'single-leg-squats',
      name: 'Single Leg Squats',
      reps: 8,
      sets: 3,
      restTime: 90,
      instructions: 'Stand on one leg, lower into a squat position, then return to standing. Switch legs.',
      difficulty: 'advanced',
      targetMuscles: ['quadriceps', 'glutes', 'hamstrings'],
    },
    {
      id: 'diamond-pushups',
      name: 'Diamond Push-ups',
      reps: 10,
      sets: 3,
      restTime: 75,
      instructions: 'Form a diamond with your hands and perform push-ups, targeting triceps.',
      difficulty: 'intermediate',
      targetMuscles: ['triceps', 'chest', 'shoulders'],
    },
    {
      id: 'reverse-lunges',
      name: 'Reverse Lunges',
      reps: 14,
      sets: 3,
      restTime: 45,
      instructions: 'Step backward into a lunge, then return to starting position. Alternate legs.',
      difficulty: 'beginner',
      targetMuscles: ['quadriceps', 'glutes', 'hamstrings'],
    },
    {
      id: 'bulgarian-split-squats',
      name: 'Bulgarian Split Squats',
      reps: 10,
      sets: 3,
      restTime: 60,
      instructions: 'Place rear foot on elevated surface, lower into single-leg squat.',
      difficulty: 'intermediate',
      targetMuscles: ['quadriceps', 'glutes'],
    },
    {
      id: 'archer-pushups',
      name: 'Archer Push-ups',
      reps: 6,
      sets: 3,
      restTime: 90,
      instructions: 'Wide-grip push-up shifting weight to one arm at a time.',
      difficulty: 'advanced',
      targetMuscles: ['chest', 'shoulders', 'triceps'],
    },
    {
      id: 'jump-squats',
      name: 'Jump Squats',
      reps: 15,
      sets: 3,
      restTime: 60,
      instructions: 'Perform a squat then explode up into a jump. Land softly.',
      difficulty: 'intermediate',
      targetMuscles: ['quadriceps', 'glutes', 'calves'],
    },
  ],
  
  // PURE MOBILITY - Flexibility and range of motion only
  mobility: [
    {
      id: 'downwarddog',
      name: 'Downward Dog',
      duration: 60,
      sets: 3,
      restTime: 30,
      instructions: 'Start on hands and knees. Lift hips up and back, straightening legs to form an inverted V.',
      difficulty: 'beginner',
      targetMuscles: ['shoulders', 'hamstrings', 'calves'],
    },
    {
      id: 'warrior1',
      name: 'Warrior I',
      duration: 45,
      sets: 2,
      restTime: 15,
      instructions: 'Step one foot forward into a lunge. Raise arms overhead. Hold and switch sides.',
      difficulty: 'beginner',
      targetMuscles: ['hip flexors', 'shoulders'],
    },
    {
      id: 'childpose',
      name: 'Child\'s Pose',
      duration: 90,
      sets: 1,
      restTime: 0,
      instructions: 'Kneel and sit back on heels. Fold forward, extending arms in front. Rest and breathe.',
      difficulty: 'beginner',
      targetMuscles: ['back', 'hips'],
    },
    {
      id: 'cat-cow',
      name: 'Cat-Cow Stretch',
      reps: 15,
      sets: 2,
      restTime: 30,
      instructions: 'On hands and knees, arch and round your back alternately, moving with your breath.',
      difficulty: 'beginner',
      targetMuscles: ['spine', 'back'],
    },
    {
      id: 'hip-circles',
      name: 'Hip Circles',
      reps: 10,
      sets: 2,
      restTime: 30,
      instructions: 'Stand with hands on hips, make large circles with your hips in both directions.',
      difficulty: 'beginner',
      targetMuscles: ['hips', 'lower back'],
    },
    {
      id: 'shoulder-rolls',
      name: 'Shoulder Rolls',
      reps: 15,
      sets: 2,
      restTime: 30,
      instructions: 'Roll your shoulders backward and forward in large circles.',
      difficulty: 'beginner',
      targetMuscles: ['shoulders', 'upper back'],
    },
  ],
  
  // PURE MUSCULAR ENDURANCE - High rep, sustained effort
  'muscular-endurance': [
    {
      id: 'wall-sit',
      name: 'Wall Sit',
      duration: 60,
      sets: 3,
      restTime: 60,
      instructions: 'Lean against a wall with thighs parallel to ground. Hold position.',
      difficulty: 'beginner',
      targetMuscles: ['quadriceps', 'glutes'],
    },
    {
      id: 'plank-hold',
      name: 'Plank Hold',
      duration: 60,
      sets: 3,
      restTime: 30,
      instructions: 'Hold straight line from head to heels, engaging your core throughout.',
      difficulty: 'beginner',
      targetMuscles: ['core', 'shoulders'],
    },
    {
      id: 'high-rep-pushups',
      name: 'High Rep Push-ups',
      reps: 25,
      sets: 3,
      restTime: 45,
      instructions: 'Perform push-ups at a steady pace, focusing on endurance over strength.',
      difficulty: 'intermediate',
      targetMuscles: ['chest', 'shoulders', 'triceps'],
    },
    {
      id: 'high-rep-squats',
      name: 'High Rep Squats',
      reps: 40,
      sets: 3,
      restTime: 45,
      instructions: 'Perform squats at a steady pace, focusing on endurance.',
      difficulty: 'intermediate',
      targetMuscles: ['quadriceps', 'glutes'],
    },
    {
      id: 'bear-crawl',
      name: 'Bear Crawl',
      duration: 45,
      sets: 3,
      restTime: 60,
      instructions: 'Crawl forward on hands and feet, keeping knees just off the ground.',
      difficulty: 'intermediate',
      targetMuscles: ['full body endurance'],
    },
  ],
  
  // PURE BALANCE & STABILITY - Proprioception and stability
  'balance-stability': [
    {
      id: 'single-leg-stand',
      name: 'Single Leg Stand',
      duration: 30,
      sets: 3,
      restTime: 30,
      instructions: 'Stand on one leg, maintain balance. Close eyes for added difficulty.',
      difficulty: 'beginner',
      targetMuscles: ['stabilizers', 'core'],
    },
    {
      id: 'tree-pose',
      name: 'Tree Pose',
      duration: 45,
      sets: 2,
      restTime: 15,
      instructions: 'Stand on one leg, place other foot on inner thigh. Hold and switch sides.',
      difficulty: 'beginner',
      targetMuscles: ['stabilizers', 'core'],
    },
    {
      id: 'warrior3',
      name: 'Warrior III',
      duration: 30,
      sets: 2,
      restTime: 30,
      instructions: 'Balance on one leg, extend other leg back and arms forward. Switch sides.',
      difficulty: 'intermediate',
      targetMuscles: ['stabilizers', 'core', 'glutes'],
    },
    {
      id: 'bosu-squats',
      name: 'Unstable Surface Squats',
      reps: 15,
      sets: 3,
      restTime: 45,
      instructions: 'Perform squats on an unstable surface like a pillow or balance pad.',
      difficulty: 'intermediate',
      targetMuscles: ['stabilizers', 'legs'],
    },
    {
      id: 'single-leg-deadlift',
      name: 'Single Leg Deadlift',
      reps: 10,
      sets: 3,
      restTime: 45,
      instructions: 'Balance on one leg, hinge at hip and reach toward ground. Return to standing.',
      difficulty: 'intermediate',
      targetMuscles: ['stabilizers', 'hamstrings', 'glutes'],
    },
  ],
  
  // PURE SPEED - Explosive, fast movements
  speed: [
    {
      id: 'sprint-intervals',
      name: 'Sprint Intervals',
      duration: 20,
      sets: 6,
      restTime: 90,
      instructions: 'All-out sprint for 20 seconds, followed by rest period.',
      difficulty: 'advanced',
      targetMuscles: ['fast-twitch fibers'],
    },
    {
      id: 'agility-ladder',
      name: 'Agility Ladder Drills',
      duration: 30,
      sets: 4,
      restTime: 60,
      instructions: 'Quick feet movement through ladder patterns - in-in-out-out, lateral shuffles.',
      difficulty: 'intermediate',
      targetMuscles: ['legs', 'coordination'],
    },
    {
      id: 'plyometric-jumps',
      name: 'Plyometric Jumps',
      reps: 8,
      sets: 4,
      restTime: 90,
      instructions: 'Explosive jumps onto a box or platform. Focus on quick, powerful movements.',
      difficulty: 'intermediate',
      targetMuscles: ['explosive power'],
    },
    {
      id: 'speed-punches',
      name: 'Speed Punches',
      duration: 15,
      sets: 5,
      restTime: 45,
      instructions: 'Throw punches as fast as possible for 15 seconds.',
      difficulty: 'intermediate',
      targetMuscles: ['arms', 'speed'],
    },
    {
      id: 'lateral-bounds',
      name: 'Lateral Bounds',
      reps: 12,
      sets: 3,
      restTime: 60,
      instructions: 'Jump laterally from side to side, landing on one foot and immediately jumping to the other side.',
      difficulty: 'intermediate',
      targetMuscles: ['lateral power', 'legs'],
    },
    {
      id: 'explosive-pushups',
      name: 'Explosive Push-ups',
      reps: 8,
      sets: 4,
      restTime: 90,
      instructions: 'Push up explosively, hands leaving the ground. Land softly.',
      difficulty: 'advanced',
      targetMuscles: ['explosive power', 'chest'],
    },
    {
      id: 'quick-feet',
      name: 'Quick Feet',
      duration: 20,
      sets: 6,
      restTime: 40,
      instructions: 'Run in place as fast as possible, focusing on foot speed.',
      difficulty: 'intermediate',
      targetMuscles: ['legs', 'coordination'],
    },
    {
      id: 'tuck-jumps',
      name: 'Tuck Jumps',
      reps: 10,
      sets: 4,
      restTime: 75,
      instructions: 'Jump up bringing knees to chest, land softly and immediately repeat.',
      difficulty: 'intermediate',
      targetMuscles: ['explosive power', 'legs'],
    },
    {
      id: 'broad-jumps',
      name: 'Broad Jumps',
      reps: 6,
      sets: 4,
      restTime: 90,
      instructions: 'Jump forward as far as possible, land in squat position.',
      difficulty: 'intermediate',
      targetMuscles: ['explosive power', 'legs'],
    },
  ],
  
  // COMBINED FOCUS WORKOUTS - Mix of 2-3 pillars
  'cardio-strength': [
    {
      id: 'burpees',
      name: 'Burpees',
      reps: 10,
      sets: 3,
      restTime: 90,
      instructions: 'Squat down, jump back to plank, do a push-up, jump forward, then jump up with arms overhead.',
      difficulty: 'intermediate',
      targetMuscles: ['cardiovascular', 'full body strength'],
    },
    {
      id: 'mountain-climbers',
      name: 'Mountain Climbers',
      reps: 20,
      sets: 3,
      restTime: 45,
      instructions: 'Start in plank position. Alternate bringing knees to chest in a running motion.',
      difficulty: 'beginner',
      targetMuscles: ['cardiovascular', 'core strength'],
    },
    {
      id: 'squat-jumps',
      name: 'Squat Jumps',
      reps: 15,
      sets: 3,
      restTime: 60,
      instructions: 'Perform a squat, then explode up into a jump. Land softly and repeat.',
      difficulty: 'intermediate',
      targetMuscles: ['cardiovascular', 'leg strength'],
    },
  ],
  
  'strength-mobility': [
    {
      id: 'yoga-pushups',
      name: 'Yoga Push-ups',
      reps: 12,
      sets: 3,
      restTime: 60,
      instructions: 'Flow from downward dog to plank to upward dog, then back to downward dog.',
      difficulty: 'intermediate',
      targetMuscles: ['strength', 'flexibility'],
    },
    {
      id: 'deep-squat-hold',
      name: 'Deep Squat Hold',
      duration: 45,
      sets: 3,
      restTime: 45,
      instructions: 'Squat down as deep as possible and hold, working on hip and ankle mobility.',
      difficulty: 'beginner',
      targetMuscles: ['leg strength', 'hip mobility'],
    },
  ],
  
  'balance-strength': [
    {
      id: 'single-leg-squats',
      name: 'Single Leg Squats',
      reps: 8,
      sets: 3,
      restTime: 90,
      instructions: 'Stand on one leg, lower into a squat position, then return to standing.',
      difficulty: 'advanced',
      targetMuscles: ['balance', 'leg strength'],
    },
    {
      id: 'plank-leg-lifts',
      name: 'Plank with Leg Lifts',
      reps: 10,
      sets: 3,
      restTime: 45,
      instructions: 'Hold plank position and lift one leg at a time, maintaining balance.',
      difficulty: 'intermediate',
      targetMuscles: ['core strength', 'stability'],
    },
  ],
};

export const SAMPLE_EXERCISES: WorkoutExercise[] = [
  ...EXERCISE_DATABASE.strength.slice(0, 2),
  ...EXERCISE_DATABASE.cardio.slice(0, 1),
  ...EXERCISE_DATABASE['balance-stability'].slice(0, 1),
];